<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="GREENVILLE" ignored="0" name="Surefire test" tests="3" failures="1" timestamp="18 жовт. 2017 10:55:15 GMT" time="0.053" errors="0">
  <testcase name="first" time="0.018" classname="samples.SampleTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
	at samples.SampleTest.first(SampleTest.java:15)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- first -->
  <testcase name="second" time="0.0" classname="samples.SampleTest"/>
  <testcase name="third" time="0.001" classname="samples.SampleTest"/>
</testsuite> <!-- Surefire test -->
